"""database init

Revision ID: f4ef43201718
Revises: 
Create Date: 2021-11-15 22:26:49.557904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4ef43201718'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumer_id'), 'consumer', ['id'], unique=False)
    op.create_table('cash_deposit',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('deposit_amount', sa.Integer(), nullable=False),
    sa.Column('secret', sa.String(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ack_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_canceled', sa.Boolean(), nullable=False),
    sa.Column('payment_key', sa.String(), nullable=True),
    sa.Column('consumer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['consumer_id'], ['consumer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cash_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('usage_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consumer_id'], ['consumer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_usage_id'), 'cash_usage', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cash_usage_id'), table_name='cash_usage')
    op.drop_table('cash_usage')
    op.drop_table('cash_deposit')
    op.drop_index(op.f('ix_consumer_id'), table_name='consumer')
    op.drop_table('consumer')
    # ### end Alembic commands ###
